---
- hosts: "{{ current_hostname }}"
  become: True
  gather_facts: true
  vars_files:
    - vars/main.yml

  tasks:
  - name: "Deploy NFS Client"
    action: apt pkg=nfs-common state=present
    
  - name: Ensure rpcbind is running (Ubuntu Trusty Tahr or newer)
    action: service name=rpcbind state=started enabled=yes
    when: ansible_lsb.major_release is defined and ansible_lsb.major_release|int >= 14

  - name: Ensure {{nfs_mountpoint}} directory exists
    action: file path={{nfs_mountpoint}} state=directory
   
  
  - shell: if [ -z "$nfsoptions" ]; then  echo rw,sync,nfsvers=3; else echo $nfsoptions; fi
    register: _nfsopts
   
    
  - name: configure /etc/fstab on clients for {{nfs_mountpoint}} on {{nfsserver}}:{{nfspath}}
    action: mount name={{nfs_mountpoint}} src={{nfsserver}}:{{nfspath}} fstype=nfs opts={{_nfsopts.stdout}} state=mounted
    
  

- hosts: "{{ current_hostname }}"
  become: True
  gather_facts: true
  vars:
    domain: "{{ prestashop_lb_name }}{{ azure_suffix }}"
  vars_files:
    - vars/main.yml

  roles:
    - { role: geerlingguy.apache } 
    - { role: geerlingguy.php }
    - { role: geerlingguy.apache-php-fpm }

  tasks:
    - name: "Install prestashop default shop"
      shell: >
        php {{ prestashop_dir }}/install/index_cli.php
        --domain="{{ domain | quote }}"
        --db_server="{{ groups['master'][0] }}"
        --db_name="{{ prestashop_dbname | quote }}"
        --db_user="{{ prestashop_user | quote }}"
        --db_password="{{ prestashop_password | quote }}"
        --firstname="{{ prestashop_firstname | quote }}"
        --lastname="{{ prestashop_lastname | quote }}"
        --password="{{ prestashop_password | quote }}"
        --email="{{ prestashop_email | quote }}"
        --newsletter=0
        --send_email=0
      when: current_hostname == "{{ groups['front'][0] }}"
      register: php_result
        
    - name: "Remove Install Directory"
      file: path="{{ prestashop_dir }}/install" state=absent
      when: php_result is defined and ( current_hostname == "{{ groups['front'][0] }}" and php_result.rc == 0 )
      
    - name: "Finalize files permission on {{ documentroot }}" 
      file: dest="{{ documentroot }}" state=directory 
            owner="{{ prestashop_owner }}" group="{{ prestashop_group }}"
            recurse=yes 
