---
- hosts: all
  become: True
  gather_facts: true
  vars_files:
    - vars/main.yml

  roles:
    - { role: ansible-init-raid } 
    - { role: geerlingguy.nfs }


  tasks:
    - name: "Create root prestashop directory for archive"
      file: path="{{ documentroot }}" state=directory mode="u=rwx,g=rx,o=rx" owner="{{ prestashop_owner }}" group="{{ prestashop_group }}"
    
- hosts: all
  become: True
  gather_facts: true
  vars_files:
    - vars/main.yml

  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }
    
    