---
- hosts: all
  become: True
  gather_facts: true
  vars_files:
    - vars/main.yml

  roles:
    - { role: ansible-init-raid } 
    - { role: geerlingguy.nfs }


  tasks:
    - name: "Create root prestashop directory for archive"
      file: path="{{ documentroot }}" state=directory mode="u=rwx,g=rx,o=rx" owner="{{ prestashop_owner }}" group="{{ prestashop_group }}"

    - name: "Create ansible shareable config files"
      file: path="{{ raid_mountpoint }}/etc/ansible" state=directory mode="u=rwx,g=rx,o=rx" owner="root"

    - name: "Check if hostfile exists"
      action: stat path="/etc/ansible/hosts"
      register: file
      ignore_errors: True

    - name: "Copy host file to nfs share"
      copy: src="/etc/ansible/hosts" dest="{{ raid_mountpoint }}/etc/ansible/"
      when: file.stat.exists

    - name: "Check if etc hosts exists"
      action: stat path="/etc/hosts"
      register: hosts
      ignore_errors: True

    - name: "Copy hosts file to nfs share"
      copy: src="/etc/hosts" dest="{{ raid_mountpoint }}/etc/"
      when: hosts.stat.exists

- hosts: all
  become: True
  gather_facts: true
  vars_files:
    - vars/main.yml

  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }
